data_warehouse:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_DB_NAME') }}"
      host: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_HOST') }}"
      password: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_PASSWORD') }}"
      port: 5439
      schema: staging
      threads: 1
      type: redshift
      user: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_USER') }}"

